"""
alerts.py — Email alert placeholder for production deployment.

Formats today's high-conviction picks into an HTML string.
SMTP integration is scaffolded but requires credentials to activate.
"""

from config import CONFIDENCE_THRESHOLD


def format_html_alert(signals: list[dict]) -> str:
    """
    Format screener picks into an HTML email body.

    Parameters
    ----------
    signals : list of dicts with keys: ticker, action, confidence, direction
    """
    rows = ""
    for s in signals:
        color = "#2ecc71" if s["direction"] == "BUY" else "#e74c3c"
        rows += f"""
        <tr>
            <td style="padding:8px;border:1px solid #ddd;">{s['ticker']}</td>
            <td style="padding:8px;border:1px solid #ddd;">{s['action']:+.4f}</td>
            <td style="padding:8px;border:1px solid #ddd;font-weight:bold;">{s['confidence']}/10</td>
            <td style="padding:8px;border:1px solid #ddd;color:{color};font-weight:bold;">
                {s['direction']}
            </td>
        </tr>"""

    html = f"""
    <html>
    <body style="font-family:Arial,sans-serif;background:#f9f9f9;padding:20px;">
        <h2 style="color:#2c3e50;">🎯 Fluid-Geometric Sniper — Daily Picks</h2>
        <p>Confidence Threshold: <strong>{CONFIDENCE_THRESHOLD}/10</strong></p>
        <p>Stocks qualifying for tomorrow's open:</p>
        <table style="border-collapse:collapse;width:100%;max-width:600px;">
            <tr style="background:#34495e;color:white;">
                <th style="padding:10px;border:1px solid #ddd;">Ticker</th>
                <th style="padding:10px;border:1px solid #ddd;">Action Signal</th>
                <th style="padding:10px;border:1px solid #ddd;">Confidence</th>
                <th style="padding:10px;border:1px solid #ddd;">Direction</th>
            </tr>
            {rows}
        </table>
        <p style="color:#7f8c8d;font-size:12px;margin-top:20px;">
            Generated by Fluid-Geometric Trading System. Not financial advice.
        </p>
    </body>
    </html>
    """
    return html


def send_email_alert(signals: list[dict]) -> None:
    """
    Placeholder for email delivery.

    To activate, configure SMTP credentials below and uncomment the send block.
    """
    html = format_html_alert(signals)
    print(f"\n📧  Email alert prepared ({len(signals)} picks).")
    print("    To activate delivery, configure SMTP in alerts.py.")

    # ── Uncomment below to enable email delivery ─────────────
    # import smtplib
    # from email.mime.multipart import MIMEMultipart
    # from email.mime.text import MIMEText
    #
    # SMTP_HOST = "smtp.gmail.com"
    # SMTP_PORT = 587
    # SMTP_USER = "your_email@gmail.com"
    # SMTP_PASS = "your_app_password"
    # TO_EMAIL   = "recipient@example.com"
    #
    # msg = MIMEMultipart("alternative")
    # msg["Subject"] = "🎯 Fluid-Geometric Sniper Picks"
    # msg["From"] = SMTP_USER
    # msg["To"] = TO_EMAIL
    # msg.attach(MIMEText(html, "html"))
    #
    # with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
    #     server.starttls()
    #     server.login(SMTP_USER, SMTP_PASS)
    #     server.sendmail(SMTP_USER, TO_EMAIL, msg.as_string())
    # print("    ✓ Email sent!")
